ROL_SUPER_ADMINISTRADOR = "super_administrador"
ROL_COORDINACION_FINANCIERA = "coordinacion_financiera"
ROL_CONCILIACION = "conciliacion"

ROLES_PRIMERA_VERSION = (
    ROL_SUPER_ADMINISTRADOR,
    ROL_COORDINACION_FINANCIERA,
    ROL_CONCILIACION,
)
